OSD-9241 add support for ZONE_ID deployment param
openshift/certman-operator pull request #210
Opened 2021-12-07 18:00 UTC by yithian

2021-12-07 19:46 UTC, dustman9000 commented on hack/olm-registry/olm-artifacts-template.yaml
> +<<<<<<< HEAD
Looks like a merge conflict

2021-12-07 19:51 UTC, yithian commented on hack/olm-registry/olm-artifacts-template.yaml
> +<<<<<<< HEAD
whoops, good catch, thanks

2021-12-07 20:28 UTC, yithian commented
/retest

2021-12-07 20:29 UTC, dustman9000 commented on deploy/operator.yaml
> +            - name: ZONE_ID
Let's rename this to HOSTED_ZONE_ID to avoid confusion...

2021-12-08 20:15 UTC, yithian commented
/retest

2021-12-09 00:50 UTC, dustman9000 commented on hack/olm-registry/olm-artifacts-template.yaml
> +        value: ${ZONE_ID}
Should be HOSTED_ZONE_ID
```suggestion
        value: ${HOSTED_ZONE_ID}
```

2021-12-09 00:51 UTC, dustman9000 commented on pkg/controller/certificaterequest/certificaterequest_controller.go
> +		reqLogger.Info("running in FedRAMP zone: %s", fedramp_hosted_zone_id)
Check for zero length string?

2021-12-09 00:52 UTC, dustman9000 requested changes
Need to fix the parameter expansion from ZONE_ID to HOSTED_ZONE_ID

2021-12-09 15:03 UTC, dustman9000 commented
/label tide/merge-method-squash

2021-12-09 15:03 UTC, dustman9000 commented
/lgtm

2021-12-09 15:24 UTC, merged