[WIP] OSD-10349 better tests
openshift/certman-operator pull request #220
Opened 2022-03-29 15:45 UTC by yithian

2022-03-29 15:45 UTC, yithian commented
/hold

2022-03-29 15:46 UTC, yithian commented
i'm opening this PR early for ease of tracking test coverage across the whole project rather than file-by-file, the way `go test ./...` does

2022-03-30 17:50 UTC, dustman9000 commented
/label tide/merge-method-squash

2022-03-31 16:33 UTC, yithian commented
/retest

2022-03-31 20:35 UTC, fahlmant requested changes
Please provide a description

2022-04-13 20:35 UTC, yithian commented
/hold cancel

2022-04-27 18:49 UTC, merged