Update MetricCertValidDuration for all CertificateRequests
openshift/certman-operator pull request #294
Opened 2024-09-11 04:56 UTC by anispate

Update MetricCertValidDuration for all CertificateRequests including the one with clusters in the hibernating and error states

2024-09-12 17:33 UTC, anispate commented
/retest

2024-09-17 22:24 UTC, clcollins requested changes

2024-09-18 17:03 UTC, anispate commented on controllers/certificaterequest/certificaterequest_controller.go
> +		// Set CertValidDuration to 0 for certificates being deleted
This is configured in the app-interface about alert creation and when we should trigger the alert to fire. Therefore, not required it here.

2024-09-20 18:49 UTC, clcollins commented
/lgtm
/approve

2024-09-20 18:52 UTC, merged